### PR TITLE
prevent multiple simultaneous memberships

### PR DESCRIPTION
**Pull request by Qelxiros**
Check one:
- [x] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):

This change prevents current active and alumni members from reentering the introductory process, thereby preventing an opportunity for constitutional ambiguity.

### CODE REVIEW

**Review by rhochgraf21 — COMMENTED** [review]
This handles the cases I was anticipating. One question however: should Advisory members be allowed to become intro members if they become students by taking a class alongside their work duties at RIT?

I would not expect that RIT would permit this, but do we want to leave the door open to that from our end?

**Comment by ikopke23** [comment]
I would argue that since Advisory Members are not formally excluded in the statement they could become intro members.

**Comment by Qelxiros** [comment]
Yep, I don't think we should prohibit Advisory Members from entering the intro process because it doesn't create loopholes in the same way as Alumni/Active Members. It seems unlikely that RIT would allow it, but it's not the place of this document to codify that.

**Review by esoccoli — APPROVED** [review]
lgtm

**Pull request merged**
