### PR TITLE
1 sentence = 1 line

### PR DESCRIPTION
**Pull request by gambogi**
Current diffs can be difficult to read because every paragraph inhabits
a single line. Giving each statement a line should make it easier to
track changes in the statement

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
Can you update this with the new changes? I think this is a good idea and would probably :+1: a working version of it.

**Comment by gambogi** [comment]
Yeah, I'll update it tomorrow

**Comment by gambogi** [comment]
@liam-middlebrook This is ready for merge

**Comment by liam-middlebrook** [comment]
@gambogi re-compile the bylaws and then this lgtm! :+1:

**Comment by gambogi** [comment]
done

**Pull request merged**
