### PR TITLE
Replaced all instances of Chairman with Chairperson

### PR DESCRIPTION
**Pull request by andreweggleston**
Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [x] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):
Makes chairman inclusive!

### CODE REVIEW

**Comment by saucetray** [comment]
Why not rename to president and put it through house

**Comment by saucetray** [comment]
I am hosting an informal poll tomorrow at house meeting to determine the following way to define the chairman:

*Chairman
*Chairwoman
*Chairperson
*Chair
* [Whatever Anyone Else Suggests]

**Comment by andreweggleston** [comment]
This looks reaaally stupid with Chair. People seemed to like it but also didn't actually read it....

**Comment by devinmatte** [comment]
Chair would be okay if we did not use chair in other instances (chair of a vote). It becomes more confusing in text.
It doesn't change what we call them (chairman, Chairwoman, chairperson) but I think the text should be chairperson as to not conflict with the existing uses of chair in the document

**Comment by mxmeinhold** [comment]
Resolved by #172

**Pull request closed without merging**
