### PR TITLE
constitution: by-laws don't exist anymore

### PR DESCRIPTION
**Pull request by Mstrodl**
Check one:
- [x] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):

By-laws don't exist anymore, we shouldn't still refer to them here.

### CODE REVIEW

**Review by galenguyer — APPROVED** [review]

**Comment by jabbate19** [comment]
This is a non semantic change

**Review by mxmeinhold — APPROVED** [review]

**Comment by mxmeinhold** [comment]
It's semantic. It changes the meaning of the text.

**Comment by JayHors** [comment]
To help clarify further, if something in the constitution refers to an outdated or no longer observed practice, it would not really change anything about current house practices, but would by definition be a semantic change.

**Comment by SpencerCreveling** [comment]
Amendment #217, By-laws don't exist anymore, has passed with the following results!
Quorum - 42 votes (2/3rds of 64)
Threshold to pass - 30 votes (2/3rds of 46 non-abstain votes cast)
Pass - 46 votes (92%)
Abstain - 4 votes (8%)

**Pull request merged**
