### PR TITLE
Revised Packet Text

### PR DESCRIPTION
**Pull request by TalCohen**
Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [X] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):

Made the composition of the packet more specific so freshmen that are given Active Membership after their introductory evaluation are still considered in the same Introductory Members section.

### CODE REVIEW

**Comment by gambogi** [comment]
Needs merge conflicts to be resolved otherwise lgtm

**Comment by liam-middlebrook** [comment]
Ping! What's the status on this? Are you planning on bringing it to ballot this Sunday in order to have the voting process complete before introductory evaluations?

**Comment by TalCohen** [comment]
I wasn't planning on having this voted on, but just merged in as seen above.

**Comment by liam-middlebrook** [comment]
Oh, sorry I didn't realize you had changed the checkbox from non-semantic to semantic from once you had submitted it. Can you rebase your changes to remove the merge conflicts?

**Pull request merged**
