### PR TITLE
Remove Housing Evaluations

### PR DESCRIPTION
**Pull request by liam-middlebrook**
Members will now receive two Housing Points upon receiving a Passing status for
Membership Evaluations.

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
Closing for now. If people are interested in the future I would also recommend giving alumni a way to get housing points.

**Comment by jeid64** [comment]
This is coming up for vote this Sunday.

**Comment by liam-middlebrook** [comment]
@jeid64 I never got your actual copy of this change. I'm going to close this PR until I've received that commit.

**Comment by rswiernik** [comment]
I think it might be a good idea to make an issue for this, that way it doesn't just fall through the cracks.

**Pull request closed without merging**
