### PR TITLE
Adds the ability for eboard or the evaluations director to remove a m…

### PR DESCRIPTION
**Pull request by Lontronix**
…ember from the list of required signatures (5.D.2.A.2)

Check one:
- [x] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):

### CODE REVIEW

**Review by mxmeinhold — CHANGES_REQUESTED** [review]
Please see the readme regarding style
`One sentence, one line. In general, follow the pattern of the existing document.`

**Comment by Lontronix** [comment]
fixed formatting issues, do you want me to squash them into one commit?

**Review by mxmeinhold — CHANGES_REQUESTED** [review]
You have a trailing space on each line that you split.

**Comment by Lontronix** [comment]
trailing space removed, your welcome @mxmeinhold

**Pull request closed without merging**
