### PR TITLE
Merge the by-laws into the articles

### LINKED ISSUE #147: References to other parts of the Constitution and By-Laws don't specify which document they are referring to
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Constitution 3.A.2 contains "the selection process as defined in 4.B." the 4.B is "linked" to Section 4.B "Closed Executive Board" which is clearly not the selection process. I assume that this 4.B is referring to By-Laws 4.B, which are about the selection process. I propose this "link" should be removed or changed to be a link to the By-Laws (if possible).

Similar problems are in the documents as a whole, with both documents using the same numbering system and not specifying which document is being referred to. I propose that there should be some means to differentiating which document is being referred to.

### PR DESCRIPTION
**Pull request by mxmeinhold**
Check one:
- [x] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s): Deletes the by-laws and places their content into the articles.

Resolves #147

### CODE REVIEW

**Comment by bmbowdish** [comment]
Can you link a PDF of what this looks like?

**Comment by bmbowdish** [comment]
also could hear some arguments as to why this is a completely non-semantic change.

**Comment by devinmatte** [comment]
@bmbowdish I'm more of the opinion that it is semantic, however as it is going to be merged into the committee branch, it will be a part of a semantic change requiring a house vote either way

**Comment by bmbowdish** [comment]
Someone will have to go through the document and fix all the links that will probably break.

**Comment by mxmeinhold** [comment]
I'd say this is semantic since it removes of the organisational text specifying the by-laws.

The new document is available at https://csh.rit.edu/~mom/Constitution/articles.pdf

**Comment by mxmeinhold** [comment]
I have not preformed an exhaustive examination of the links, but it appears that the only broken link is the Housing Evaluations link as referenced in #150

**Comment by mxmeinhold** [comment]
Rebased to resolve merge conflicts.

**Pull request merged**
