### PR TITLE
Failure to Get an Account After Packet is Failure to Complete Introductory Evaluations

### PR DESCRIPTION
**Pull request by liam-middlebrook**
Check one:
- [X] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):

### CODE REVIEW

**Comment by venku122** [comment]
I feel this is going to be rather controversial. On one hand, intro members with less than 60% rarely pass a 10 week evaluation. On the other hand, the other aspects of the introductory process are also critical evaluations criteria and the 10 week process allows for a more thorough evaluation of the applicant.

**Comment by liam-middlebrook** [comment]
I personally believe that it makes more sense for introductory members whom do not receive an account at the end of their introductory packet currently to resign and re-apply. I think that the stigma of such a low packet score, in combination to the difficulty of not having an account make continuing with 8 more weeks of the process unfair to the introductory member who for lack of a better term "has the odds against them."

**Comment by bmbowdish** [comment]
I worry this would make even more freshmen stop doing packet once they reached the 60% threshold. 

On the other hand, I think this would help people know the majority of floor by the time 10 weeks rolls around, which was an issue this year.

**Comment by gambogi** [comment]
No. It's not common but that's not a good reason to ban it. Josh Robbins passed easily a few years ago and didn't reach the minimum threshold for an account.

**Comment by bmbowdish** [comment]
If a member fails, they can reapply. Additionally, if they reapply and retake the packet they may even be involved at the same 10 weeks.

**Comment by VictoriaWeaver** [comment]
https://webnews.csh.rit.edu/#!/csh.committee.eval/1304

**Comment by liam-middlebrook** [comment]
Failed 4 - 39

**Pull request closed without merging**
